#[derive(Hash, Eq, PartialEq, Debug, Deserialize, Serialize)]
pub struct Card {
    pub name: String,
    pub value: u16
}

pub fn create_deck() -> Vec<Card> {
    vec![
        Card {name: "ACE".to_owned(),    value: 11},
        Card {name: "TWOS".to_owned(),   value: 2 },
        Card {name: "THREES".to_owned(), value: 3 },
        Card {name: "FOURS".to_owned(),  value: 4 },
        Card {name: "FIVES".to_owned(),  value: 5 },
        Card {name: "SIXES".to_owned(),  value: 6 },
        Card {name: "SEVENS".to_owned(), value: 7 },
        Card {name: "EIGHTS".to_owned(), value: 8 },
        Card {name: "NINES".to_owned(),  value: 9 },
        Card {name: "TENS".to_owned(),   value: 10},
        Card {name: "JACKS".to_owned(),  value: 10},
        Card {name: "KINGS".to_owned(),  value: 10},
        Card {name: "QUEENS".to_owned(), value: 10},
        Card {name: "ACE".to_owned(),    value: 11},
        Card {name: "TWOS".to_owned(),   value: 2 },
        Card {name: "THREES".to_owned(), value: 3 },
        Card {name: "FOURS".to_owned(),  value: 4 },
        Card {name: "FIVES".to_owned(),  value: 5 },
        Card {name: "SIXES".to_owned(),  value: 6 },
        Card {name: "SEVENS".to_owned(), value: 7 },
        Card {name: "EIGHTS".to_owned(), value: 8 },
        Card {name: "NINES".to_owned(),  value: 9 },
        Card {name: "TENS".to_owned(),   value: 10},
        Card {name: "JACKS".to_owned(),  value: 10},
        Card {name: "KINGS".to_owned(),  value: 10},
        Card {name: "QUEENS".to_owned(), value: 10},
        Card {name: "ACE".to_owned(),    value: 11},
        Card {name: "TWOS".to_owned(),   value: 2 },
        Card {name: "THREES".to_owned(), value: 3 },
        Card {name: "FOURS".to_owned(),  value: 4 },
        Card {name: "FIVES".to_owned(),  value: 5 },
        Card {name: "SIXES".to_owned(),  value: 6 },
        Card {name: "SEVENS".to_owned(), value: 7 },
        Card {name: "EIGHTS".to_owned(), value: 8 },
        Card {name: "NINES".to_owned(),  value: 9 },
        Card {name: "TENS".to_owned(),   value: 10},
        Card {name: "JACKS".to_owned(),  value: 10},
        Card {name: "KINGS".to_owned(),  value: 10},
        Card {name: "QUEENS".to_owned(), value: 10},
        Card {name: "ACE".to_owned(),    value: 11},
        Card {name: "TWOS".to_owned(),   value: 2 },
        Card {name: "THREES".to_owned(), value: 3 },
        Card {name: "FOURS".to_owned(),  value: 4 },
        Card {name: "FIVES".to_owned(),  value: 5 },
        Card {name: "SIXES".to_owned(),  value: 6 },
        Card {name: "SEVENS".to_owned(), value: 7 },
        Card {name: "EIGHTS".to_owned(), value: 8 },
        Card {name: "NINES".to_owned(),  value: 9 },
        Card {name: "TENS".to_owned(),   value: 10},
        Card {name: "JACKS".to_owned(),  value: 10},
        Card {name: "KINGS".to_owned(),  value: 10},
        Card {name: "QUEENS".to_owned(), value: 10},
        Card {name: "ACE".to_owned(),    value: 11},
        Card {name: "TWOS".to_owned(),   value: 2 },
        Card {name: "THREES".to_owned(), value: 3 },
        Card {name: "FOURS".to_owned(),  value: 4 },
        Card {name: "FIVES".to_owned(),  value: 5 },
        Card {name: "SIXES".to_owned(),  value: 6 },
        Card {name: "SEVENS".to_owned(), value: 7 },
        Card {name: "EIGHTS".to_owned(), value: 8 },
        Card {name: "NINES".to_owned(),  value: 9 },
        Card {name: "TENS".to_owned(),   value: 10},
        Card {name: "JACKS".to_owned(),  value: 10},
        Card {name: "KINGS".to_owned(),  value: 10},
        Card {name: "QUEENS".to_owned(), value: 10},
    ]
}
