#[derive(Hash, Eq, PartialEq, Debug)]
pub struct Card {
    pub name: &'static str,
    pub value: u16
}

pub fn create_deck() -> Vec<Card> {
    vec![
        Card {name: "ACE",    value: 11},
        Card {name: "TWOS",   value: 2 },
        Card {name: "THREES", value: 3 },
        Card {name: "FOURS",  value: 4 },
        Card {name: "FIVES",  value: 5 },
        Card {name: "SIXES",  value: 6 },
        Card {name: "SEVENS", value: 7 },
        Card {name: "EIGHTS", value: 8 },
        Card {name: "NINES",  value: 9 },
        Card {name: "TENS",   value: 10},
        Card {name: "JACKS",  value: 10},
        Card {name: "KINGS",  value: 10},
        Card {name: "QUEENS", value: 10},
        Card {name: "ACE",    value: 11},
        Card {name: "TWOS",   value: 2 },
        Card {name: "THREES", value: 3 },
        Card {name: "FOURS",  value: 4 },
        Card {name: "FIVES",  value: 5 },
        Card {name: "SIXES",  value: 6 },
        Card {name: "SEVENS", value: 7 },
        Card {name: "EIGHTS", value: 8 },
        Card {name: "NINES",  value: 9 },
        Card {name: "TENS",   value: 10},
        Card {name: "JACKS",  value: 10},
        Card {name: "KINGS",  value: 10},
        Card {name: "QUEENS", value: 10},
        Card {name: "ACE",    value: 11},
        Card {name: "TWOS",   value: 2 },
        Card {name: "THREES", value: 3 },
        Card {name: "FOURS",  value: 4 },
        Card {name: "FIVES",  value: 5 },
        Card {name: "SIXES",  value: 6 },
        Card {name: "SEVENS", value: 7 },
        Card {name: "EIGHTS", value: 8 },
        Card {name: "NINES",  value: 9 },
        Card {name: "TENS",   value: 10},
        Card {name: "JACKS",  value: 10},
        Card {name: "KINGS",  value: 10},
        Card {name: "QUEENS", value: 10},
        Card {name: "ACE",    value: 11},
        Card {name: "TWOS",   value: 2 },
        Card {name: "THREES", value: 3 },
        Card {name: "FOURS",  value: 4 },
        Card {name: "FIVES",  value: 5 },
        Card {name: "SIXES",  value: 6 },
        Card {name: "SEVENS", value: 7 },
        Card {name: "EIGHTS", value: 8 },
        Card {name: "NINES",  value: 9 },
        Card {name: "TENS",   value: 10},
        Card {name: "JACKS",  value: 10},
        Card {name: "KINGS",  value: 10},
        Card {name: "QUEENS", value: 10},
        Card {name: "ACE",    value: 11},
        Card {name: "TWOS",   value: 2 },
        Card {name: "THREES", value: 3 },
        Card {name: "FOURS",  value: 4 },
        Card {name: "FIVES",  value: 5 },
        Card {name: "SIXES",  value: 6 },
        Card {name: "SEVENS", value: 7 },
        Card {name: "EIGHTS", value: 8 },
        Card {name: "NINES",  value: 9 },
        Card {name: "TENS",   value: 10},
        Card {name: "JACKS",  value: 10},
        Card {name: "KINGS",  value: 10},
        Card {name: "QUEENS", value: 10},
    ]
}
